### ISSUE TITLE
Problem: Expand on acronyms that might not be known to all

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica-docs#52]
For example, PII (personally identifiable information?), https://github.com/artefactual/archivematica-docs/search?utf8=%E2%9C%93&q=%22PII+information%22&type=

**Comment by sevein** [comment]
Is the glossary a good venue for it? E.g. see https://www.accesstomemory.org/en/docs/2.5/user-manual/glossary/glossary/. @fiver-watson links to them using the following syntax:

    :term:`multi-repository <multi-repository system>`. 

Not sure if we have a glossary yet. See https://github.com/artefactual/atom-docs/blob/2.5/user-manual/glossary/glossary.rst.

**Comment by ross-spencer** [comment]
Glossary and inline would be great so that the user has the text expansion there in front of them, i.e. what PPI (...) is, and then can find even more information in the glossary.

**Comment by sromkey** [comment]
I don't think we have the time to implement a glossary at this point but agree that the acronym should be expanded within the text.

**Comment by sallain** [comment]
@ross-spencer I think this is something that we/I can work on as part of our continuing effort to draw the Archivematica docs more inline with the [style guide](https://github.com/artefactual/archivematica-docs/blob/c6e2619c030f518a3337a83e6295b1e41f9c0841/style_guide.md). I'm trying to clean up old issues in this repo since they're likely to get forgotten; is it okay if I close this?

(I'm addressing the specific PII example that you mention above as part of another issue.)

**Comment by ross-spencer** [comment]
Thanks for checking in @sallain, I apprecitate it. Closing as we speak!
