### ISSUE TITLE
Problem: docs do not indicate new silent AIP compression behaviour

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-docs#66]
When the new "do/do not capture output streams" behaviour is merged into AM, the docs need to explain that AIP compression is no longer capturing standard output form the compression task. This has implications for the pointer file which will now no longer include the compression output. As a result, the pointer file for AIPs with many files will now be significantly reduced in size.

See the changes to src/MCPClient/lib/clientScripts/compressAIP.py in https://github.com/artefactual/archivematica/compare/qa/1.x...dev/1.8.x-without-logs.

**Comment by sallain** [comment]
@kellyannewithane Did the above ever get addressed?

There isn't really a place in the documentation where the previous compression behaviour was described (see [here](https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/administer/dashboard-admin/#select-compression-algorithm)), nor is there a place where pointer files are really described. It would be great to have more information on what file compression actually does, and what kind of information is captured, but I'm not sure that this ticket exactly describes that (and I think it would be a nice-to-have, rather than a need-to-have).  If you agree, I think we should just close this ticket.

**Comment by kellyannewithane** [comment]
@sallain the above was written a long long time ago but I don't believe it was ever addressed.  Agreed it's a nice-to-have not a need-to-have.  We can close the ticket
